<?php

declare(strict_types=1);

require_once dirname(__DIR__) . '/tools/build-staging-package.php';
require_once dirname(__DIR__) . '/tools/verify-staging-artifact.php';
$root=dirname(__DIR__);$failures=[];$check=static function(bool$c,string$m)use(&$failures):void{if(!$c){$failures[]=$m;}};$read=static fn(string$p):string=>(string)(file_get_contents($root.'/'.$p)?:'');
$main=$read('sabri-public-experience.php');preg_match("/define\('SABRI_PUBLIC_EXPERIENCE_VERSION',\s*'([^']+)'\)/",$main,$match);$runtime=(string)($match[1]??'');$check($runtime!=='','Runtime version missing.');
try{$payload=File25_Staging_Package_Builder::discover_payload($root);}catch(Throwable$e){$payload=[];$failures[]='Payload discovery failed: '.$e->getMessage();}
foreach(['sabri-public-experience.php','assets/css/companion-token-bridge.css','includes/class-native-integration.php','includes/class-current-companion-2026-08-10.php','config/staging-dependencies.json','config/staging-test-plan.json']as$r){$check(in_array($r,$payload,true),'Staging payload missing '.$r);}foreach($payload as$p){$check(!preg_match('#(?:^|/)(?:\.git|\.github|build|coverage|docs|node_modules|tests|tools|vendor)(?:/|$)#',$p),'Development path entered staging payload: '.$p);}
$matrix=json_decode($read('config/staging-dependencies.json'),true);$check(is_array($matrix)&&($matrix['schema_version']??null)===3&&($matrix['file']??null)===25&&($matrix['runtime_version']??'')===$runtime,'Dependency matrix identity mismatch.');$check(($matrix['environment']['live_changes_allowed']??true)===false,'Matrix must prohibit live changes.');$check(($matrix['artifact_verification']['staging_acceptance_implied']??true)===false,'Artifact verification cannot imply staging acceptance.');
$modules=[];foreach((array)($matrix['modules']??[])as$m){if(is_array($m)&&isset($m['file'])){$modules[(int)$m['file']]=$m;}}foreach([0,3,6,7,8,9,10,11,12,14,18,20,21,22,23,24,25]as$f){$check(isset($modules[$f]),'Dependency matrix missing File '.$f);}
$checks=[
0=>($modules[0]['reviewed_source_commit']??'')==='c37d0b101d0912bef1f26d0daf51a414d67907c0'&&($modules[0]['required_contract_version']??'')==='1.2.2',
3=>($modules[3]['reviewed_source_commit']??'')==='b862efb94be87980e96a5b864bc5c7aec49183d9'&&($modules[3]['required_contract_version']??'')==='1.4.0',
7=>($modules[7]['reviewed_source_branch']??'')==='fix/file-07-second-fresh-80-review-20260810'&&($modules[7]['reviewed_source_commit']??'')==='b37c7c7b46f3f57b7325e075601c10bf3ced72ba'&&($modules[7]['required_contract_version']??'')==='1.2.0',
8=>($modules[8]['reviewed_source_commit']??'')==='cb302617d2a2def23de1883b8d9fead10bce7ef3'&&($modules[8]['required_canonical_contract_version']??'')==='1.1.0'&&($modules[8]['required_public_contract_version']??'')==='1.0.0',
9=>($modules[9]['reviewed_source_commit']??'')==='9103310fc93d978b6e70661f024a079fc0971003'&&($modules[9]['required_contract_version']??'')==='1.1.0',
14=>($modules[14]['reviewed_source_version']??'')==='1.4.3'&&($modules[14]['reviewed_source_branch']??'')==='review/file14-fifth-80-round-2026-08-10'&&($modules[14]['reviewed_source_commit']??'')==='907a04b25567a607e5ecb11d26e50bd0f07852be'&&($modules[14]['required_primary_color']??'')==='#087A4E',
18=>($modules[18]['reviewed_source_version']??'')==='1.2.0-RC1',20=>($modules[20]['reviewed_source_commit']??'')==='291486b22c7ed94b8be041192375b6d9b077fac5',21=>($modules[21]['reviewed_source_commit']??'')==='afeda8742d8e1ea62254823291a66f502058989c',22=>($modules[22]['reviewed_source_commit']??'')==='c3b775b66fbbda4a9dd9891d63c08c74e2178741',23=>($modules[23]['reviewed_source_commit']??'')==='a8a8c805f4730998ccb44bd95c87591836561759',24=>($modules[24]['reviewed_source_commit']??'')==='0be43b3f424d7b53865587b2770479ca33f51a0b',25=>($modules[25]['candidate_version']??'')===$runtime&&($modules[25]['canonical_primary_color']??'')==='#087A4E'&&($modules[25]['design_token_owner']??'')==='file-25'&&($modules[25]['structural_shell_owner']??'')==='file-20'];foreach($checks as$f=>$ok){$check($ok,'Current reviewed contract mismatch for File '.$f);}foreach($modules as$m){if(isset($m['staging_status'])){$check($m['staging_status']==='pending','Source evidence must not promote staging acceptance.');}}
$plan=json_decode($read('config/staging-test-plan.json'),true);$check(is_array($plan)&&($plan['schema_version']??null)===3,'Staging test plan schema 3 required.');$ids=[];foreach((array)($plan['scenarios']??[])as$s){if(is_array($s)){$ids[]=(string)($s['id']??'');}}foreach(['file00-assertions','file03-current-public-dto','file03-future-public-experience','file03-component-provider','file03-route-parity','file07-directory-visual-contract','file08-clinic-projection','file09-doctor-decision','file14-visual-consumer','file21-current-profile-timeline-contract','file22-create-edit-contract','file23-private-management-contract','file24-current-assurance-contract','companion-token-bridge']as$id){$check(in_array($id,$ids,true),'Staging plan missing '.$id);}
$verifier=$read('tools/verify-staging-artifact.php');foreach(['File25_Staging_Artifact_Verifier','Embedded manifest or dependency matrix differs from detached evidence.','Unsafe, duplicate or symbolic entry detected in workflow artifact.','Unsafe, duplicate or symbolic entry detected in inner ZIP.','MAX_INNER_TOTAL_BYTES','staging_accepted','production_accepted']as$m){$check(str_contains($verifier,$m),'Artifact verifier marker missing: '.$m);}$builder=$read('tools/build-staging-package.php');foreach(['SOURCE_DATE_EPOCH','STAGING-MANIFEST.json','ZipArchive','verify_archive','zip_entry_is_symlink','MAX_PAYLOAD_BYTES']as$m){$check(str_contains($builder,$m),'Package builder marker missing: '.$m);}
if($failures!==[]){fwrite(STDERR,"FAILED\n- ".implode("\n- ",$failures)."\n");exit(1);}echo "PASS: File 25 current release-engineering and dependency contracts\n";
