<?php

declare(strict_types=1);
$root=dirname(__DIR__);$failures=[];$check=static function(bool$c,string$m)use(&$failures):void{if(!$c){$failures[]=$m;}};$read=static function(string$p)use($root,&$failures):string{$v=@file_get_contents($root.'/'.$p);if(!is_string($v)){$failures[]='Unreadable evidence: '.$p;return '';}return$v;};
try{$ledger=json_decode($read('config/review275-354-eighty-round-ledger.json'),true,512,JSON_THROW_ON_ERROR);}catch(JsonException$e){$ledger=[];$failures[]='Invalid historical ledger: '.$e->getMessage();}
$check(($ledger['review_range']['first']??null)===275&&($ledger['review_range']['last']??null)===354&&($ledger['review_range']['count']??null)===80,'Historical cycle range changed.');$check(($ledger['defect_rounds']??null)===array_merge(range(275,316),[354]),'Historical defect ledger changed.');$check(($ledger['clean_rounds']??null)===range(317,353),'Historical clean ledger changed.');$numbers=[];foreach((array)($ledger['reviews']??[])as$row){if(is_array($row)&&is_int($row['review']??null)){$numbers[]=$row['review'];}}$check($numbers===range(275,354),'Historical reviews must remain contiguous.');foreach(['hostinger_staging_accepted','founder_staging_acceptance','production_accepted','live_deployed','operational','exact_deployed_code_verified']as$gate){$check(($ledger['external_truth'][$gate]??null)===false,'Historical external gate promoted: '.$gate);}
$native=$read('includes/class-native-integration.php');$current=$read('includes/class-current-companion-2026-08-10.php');$rest=$read('includes/class-rest-controller.php');$future=$read('includes/class-future-public-experience.php');$builder=$read('tools/build-staging-package.php');$verifier=$read('tools/verify-staging-artifact.php');
foreach(["FILE_00_MINIMUM_VERSION = '1.2.38'","FILE_03_CONTRACT_VERSION = '1.4.0'","FILE_09_CONTRACT_VERSION = '1.1.0'","FILE_08_MINIMUM_VERSION = '1.2.0'","FILE_08_CANONICAL_CONTRACT = '1.1.0'","FILE_08_PUBLIC_PROJECTION_CONTRACT = '1.1.0'",'spd_get_public_profile','gdo_file03_doctor_eligibility']as$m){$check(str_contains($native,$m),'Current native marker missing: '.$m);}foreach(['spd_get_personal_site_profile','sabri_file25_register_component_provider','professional_lifecycle']as$m){$check(str_contains($current,$m),'Current companion marker missing: '.$m);}foreach(["'ETag'","'Last-Modified'",'allow_public_request',"'status' => 429"]as$m){$check(str_contains($rest,$m),'REST marker missing: '.$m);}$check(str_contains($future,"'global_search_discovery_ranking_owner' => 'file-26'"),'File26 owner boundary missing.');foreach(['SOURCE_DATE_EPOCH','ZipArchive','zip_entry_is_symlink','MAX_PAYLOAD_BYTES']as$m){$check(str_contains($builder,$m),'Builder defense missing: '.$m);}foreach(['MAX_INNER_TOTAL_BYTES','Unsafe, duplicate or symbolic entry detected in inner ZIP.','staging_accepted','production_accepted']as$m){$check(str_contains($verifier,$m),'Verifier defense missing: '.$m);}
$matrix=json_decode($read('config/staging-dependencies.json'),true);$check(is_array($matrix)&&($matrix['schema_version']??null)===3,'Current dependency matrix schema 3 required.');$modules=[];foreach((array)($matrix['modules']??[])as$module){if(is_array($module)&&isset($module['file'])){$modules[(int)$module['file']]=$module;}}
$expected=[0=>'2fa7c022ee9cd1b65432e900579512f304532442',3=>'636e3ef965423887f810718abec3cd1c11c3659d',7=>'67c32ec4af45a7de6e3d9c1dbf0f8614d6b5a844',8=>'70541974ce0ffb16aebef557c3016eb7447662f4',9=>'a9ab697c671129be023414f5a3c32186567cb2bf',14=>'db60c4bc5c37a5c88126b78c31b34c75236f33d7',17=>'8ae656e51796d1f05865d8be5dca2480443d79ca',19=>'04078025b643ab7696e4cb4e37826bf152defa18',20=>'8a4dbcaf4fef8e926b9b834ecfde16c21a0f00ca',21=>'f2eb7e95ddea327af36ea725ffb923b029f885e6',22=>'b7a7f2e69411cbd32f0574fd12d766fb70c01b7a',23=>'dcae138e6073f4d0ff596623deb05b9940b8271b',24=>'a5b8d49968a7a5a7d6f3f4655bea541bf38a9acb',26=>'bbea3aad466792a4a6a62b53532bbd45c7c592de'];foreach($expected as$file=>$sha){$check(($modules[$file]['reviewed_source_commit']??'')===$sha,'Current exact source mismatch for File '.$file.'.');}
$check(($modules[8]['required_canonical_contract_version']??'')==='1.1.0'&&($modules[8]['required_public_contract_version']??'')==='1.1.0','Current File08 layered contract mismatch.');$check(($modules[9]['reviewed_source_branch']??'')==='main','Current File09 branch mismatch.');foreach($modules as$module){if(isset($module['staging_status'])){$check($module['staging_status']==='pending','Source evidence may not promote staging acceptance.');}}
$plan=json_decode($read('config/staging-test-plan.json'),true);$ids=[];foreach((array)($plan['scenarios']??[])as$s){if(is_array($s)){$ids[]=(string)($s['id']??'');}}foreach(['file03-future-public-experience','file03-component-provider','file03-route-parity','file08-clinic-projection','file09-doctor-decision','file21-current-profile-timeline-contract','file24-current-assurance-contract','file17-native-profile-actions','file19-notification-owner','file26-search-ranking-owner']as$id){$check(in_array($id,$ids,true),'Current staging scenario missing: '.$id);}
if($failures!==[]){fwrite(STDERR,"FAILED Reviews 275-354\n- ".implode("\n- ",$failures)."\n");exit(1);}echo "PASS: File 25 Reviews 275-354 — historical ledger preserved with sixth-cycle companion truth\n";
