<?php

declare(strict_types=1);
$root=dirname(__DIR__);$failures=[];$check=static function(bool$c,string$m)use(&$failures):void{if(!$c){$failures[]=$m;}};$read=static function(string$p)use($root,&$failures):string{$v=@file_get_contents($root.'/'.$p);if(!is_string($v)){$failures[]='Unreadable evidence: '.$p;return '';}return$v;};
try{$ledger=json_decode($read('config/review355-434-third-eighty-ledger.json'),true,512,JSON_THROW_ON_ERROR);}catch(JsonException$e){$ledger=[];$failures[]='Third-cycle ledger invalid: '.$e->getMessage();}
$expected=[355,356,357,358,359,360,361,362,363,364,365,366,367,368,370,371,372,433,434];$check(($ledger['review_range']??null)===['first'=>355,'last'=>434,'count'=>80],'Third-cycle range changed.');$check(($ledger['defect_rounds']??null)===$expected,'Third-cycle defect ledger changed.');$clean=(array)($ledger['clean_rounds']??[]);$check(count($clean)===61&&$clean[0]===369&&end($clean)===432,'Third-cycle clean ledger changed.');foreach(['hostinger_staging_accepted','founder_staging_acceptance','production_accepted','live_deployed','operational','exact_deployed_code_verified','db_version_verified','migration_state_verified_live']as$g){$check(($ledger['external_truth'][$g]??null)===false,'External truth promoted: '.$g);}
$file20=$read('includes/class-file-20-integration.php');foreach(["REVIEWED_MINIMUM_VERSION = '1.4.12'","REVIEWED_MAXIMUM_VERSION = '1.5.0'","REVIEWED_CONTRACT_VERSION = '1.0.0'","REVIEWED_SOURCE_COMMIT = '291486b22c7ed94b8be041192375b6d9b077fac5'",'sabri_shell_contract_registry']as$m){$check(str_contains($file20,$m),'File20 marker missing: '.$m);}
$design=$read('includes/class-design-system.php');foreach(["public const CONTRACT_VERSION = '1.9.0'",'sabri_shell_file25_visual_contract',"'primary_color' => '#087A4E'","'owner' => 'file-25'"]as$m){$check(str_contains($design,$m),'Design marker missing: '.$m);}
$component=$read('includes/class-component-api.php');foreach(["CONTRACT_VERSION = '1.0.0'",'MAX_PENDING_TIMELINE_PROVIDERS = 25','bind_timeline_registry','register_card_variant']as$m){$check(str_contains($component,$m),'Component API marker missing: '.$m);}
$entry=$read('sabri-public-experience.php');foreach(["'includes/class-file-20-integration.php'","'includes/class-current-companion-2026-08-10.php'",'Current_Companion_2026_08_10::register()']as$m){$check(str_contains($entry,$m),'Bootstrap marker missing: '.$m);}
$matrix=json_decode($read('config/staging-dependencies.json'),true);$modules=[];foreach((array)($matrix['modules']??[])as$module){if(is_array($module)&&isset($module['file'])){$modules[(int)$module['file']]=$module;}}$check(($modules[20]['reviewed_source_version']??'')==='1.4.12'&&($modules[20]['reviewed_source_commit']??'')==='291486b22c7ed94b8be041192375b6d9b077fac5'&&($modules[20]['required_contract_version']??'')==='1.0.0'&&($modules[20]['staging_status']??'')==='pending','File20 matrix current truth mismatch.');
$staging=json_decode($read('config/staging-test-plan.json'),true);$ids=[];foreach((array)($staging['scenarios']??[])as$s){if(is_array($s)){$ids[]=(string)($s['id']??'');}}foreach(['file20-current-shell-contract','file20-admin-parent','component-api-runtime','file03-route-parity','file03-component-provider']as$id){$check(in_array($id,$ids,true),'Staging scenario missing: '.$id);}
$verifier=$read('tools/verify-staging-artifact.php');foreach(['File25_Staging_Artifact_Verifier','MAX_INNER_TOTAL_BYTES','Unsafe, duplicate or symbolic entry detected in workflow artifact.','Unsafe, duplicate or symbolic entry detected in inner ZIP.','Embedded manifest or dependency matrix differs from detached evidence.',"reviewed_source_commit'] ?? '') === '291486b22c7ed94b8be041192375b6d9b077fac5'"]as$m){$check(str_contains($verifier,$m),'Artifact verifier marker missing: '.$m);}
$composer=$read('composer.json');$check(str_contains($composer,'tests/review355-434-third-eighty-integration.php'),'Third-cycle gate must remain governed.');$check(is_file($root.'/docs/REVIEWS-355-434-THIRD-EIGHTY-CURRENT-INTEGRATION-2026-08-10.md'),'Third-cycle human record missing.');$workflow=$read('.github/workflows/ci.yml');$check(str_contains($workflow,'actions/checkout@v5')&&str_contains($workflow,'php: ["8.0", "8.3"]'),'CI matrix drift.');
if($failures!==[]){fwrite(STDERR,"FAILED Reviews 355-434\n- ".implode("\n- ",$failures)."\n");exit(1);}echo "PASS: File 25 Reviews 355-434 — third eighty-round historical closure preserved with current verifier truth\n";
