<?php

declare(strict_types=1);
$root=dirname(__DIR__);$failures=[];$check=static function(bool$c,string$m)use(&$failures):void{if(!$c){$failures[]=$m;}};$read=static function(string$p)use($root,&$failures):string{$v=@file_get_contents($root.'/'.$p);if(!is_string($v)){$failures[]='Unreadable evidence: '.$p;return '';}return$v;};
try{$ledger=json_decode($read('config/review275-354-eighty-round-ledger.json'),true,512,JSON_THROW_ON_ERROR);}catch(JsonException$e){$ledger=[];$failures[]='Invalid historical ledger: '.$e->getMessage();}
$check(($ledger['review_range']['first']??null)===275&&($ledger['review_range']['last']??null)===354&&($ledger['review_range']['count']??null)===80,'Historical cycle range changed.');$check(($ledger['defect_rounds']??null)===array_merge(range(275,316),[354]),'Historical defect ledger changed.');$check(($ledger['clean_rounds']??null)===range(317,353),'Historical clean ledger changed.');$numbers=[];foreach((array)($ledger['reviews']??[])as$row){if(is_array($row)&&is_int($row['review']??null)){$numbers[]=$row['review'];}}$check($numbers===range(275,354),'Historical reviews must remain contiguous.');foreach(['hostinger_staging_accepted','founder_staging_acceptance','production_accepted','live_deployed','operational','exact_deployed_code_verified']as$gate){$check(($ledger['external_truth'][$gate]??null)===false,'Historical external gate promoted: '.$gate);}
$native=$read('includes/class-native-integration.php');$current=$read('includes/class-current-companion-2026-08-10.php');$rest=$read('includes/class-rest-controller.php');$future=$read('includes/class-future-public-experience.php');$builder=$read('tools/build-staging-package.php');$verifier=$read('tools/verify-staging-artifact.php');
foreach(["FILE_00_MINIMUM_VERSION = '1.2.38'","FILE_03_CONTRACT_VERSION = '1.4.0'","FILE_09_CONTRACT_VERSION = '1.1.0'","FILE_08_MINIMUM_VERSION = '1.2.0'","FILE_08_CANONICAL_CONTRACT = '1.1.0'","FILE_08_PUBLIC_PROJECTION_CONTRACT = '1.0.0'",'spd_get_public_profile','gdo_file03_doctor_eligibility']as$m){$check(str_contains($native,$m),'Current native marker missing: '.$m);}foreach(['spd_get_personal_site_profile','sabri_file25_register_component_provider','professional_lifecycle']as$m){$check(str_contains($current,$m),'Current companion marker missing: '.$m);}foreach(["'ETag'","'Last-Modified'",'allow_public_request',"'status' => 429"]as$m){$check(str_contains($rest,$m),'REST marker missing: '.$m);}$check(str_contains($future,"'global_search_discovery_ranking_owner' => 'file-26'"),'File26 owner boundary missing.');foreach(['SOURCE_DATE_EPOCH','ZipArchive','zip_entry_is_symlink','MAX_PAYLOAD_BYTES']as$m){$check(str_contains($builder,$m),'Builder defense missing: '.$m);}foreach(['MAX_INNER_TOTAL_BYTES','Unsafe, duplicate or symbolic entry detected in inner ZIP.','staging_accepted','production_accepted']as$m){$check(str_contains($verifier,$m),'Verifier defense missing: '.$m);}
$matrix=json_decode($read('config/staging-dependencies.json'),true);$check(is_array($matrix)&&($matrix['schema_version']??null)===3,'Current dependency matrix schema 3 required.');$modules=[];foreach((array)($matrix['modules']??[])as$module){if(is_array($module)&&isset($module['file'])){$modules[(int)$module['file']]=$module;}}
$expected=[0=>'c37d0b101d0912bef1f26d0daf51a414d67907c0',3=>'b862efb94be87980e96a5b864bc5c7aec49183d9',7=>'67c32ec4af45a7de6e3d9c1dbf0f8614d6b5a844',8=>'cb302617d2a2def23de1883b8d9fead10bce7ef3',9=>'9103310fc93d978b6e70661f024a079fc0971003',14=>'b9045a4229d052103a5546477f664ac88b6ff034',20=>'291486b22c7ed94b8be041192375b6d9b077fac5',21=>'afeda8742d8e1ea62254823291a66f502058989c',22=>'c3b775b66fbbda4a9dd9891d63c08c74e2178741',23=>'a8a8c805f4730998ccb44bd95c87591836561759',24=>'0be43b3f424d7b53865587b2770479ca33f51a0b'];foreach($expected as$file=>$sha){$check(($modules[$file]['reviewed_source_commit']??'')===$sha,'Current exact source mismatch for File '.$file.'.');}
$check(($modules[8]['required_canonical_contract_version']??'')==='1.1.0'&&($modules[8]['required_public_contract_version']??'')==='1.0.0','Current File08 layered contract mismatch.');$check(($modules[9]['reviewed_source_branch']??'')==='codex/file09-1.3.0-rc6-80-round-review','Current File09 branch mismatch.');foreach($modules as$module){if(isset($module['staging_status'])){$check($module['staging_status']==='pending','Source evidence may not promote staging acceptance.');}}
$plan=json_decode($read('config/staging-test-plan.json'),true);$ids=[];foreach((array)($plan['scenarios']??[])as$s){if(is_array($s)){$ids[]=(string)($s['id']??'');}}foreach(['file03-future-public-experience','file03-component-provider','file03-route-parity','file08-clinic-projection','file09-doctor-decision','file21-current-profile-timeline-contract','file24-current-assurance-contract']as$id){$check(in_array($id,$ids,true),'Current staging scenario missing: '.$id);}
if($failures!==[]){fwrite(STDERR,"FAILED Reviews 275-354\n- ".implode("\n- ",$failures)."\n");exit(1);}echo "PASS: File 25 Reviews 275-354 — historical ledger preserved with sixth-cycle companion truth\n";
